#!/bin/bash
#仅保证可在ubuntu20.04使用
screen_cryofall=$"cryofall"
cmd=$"dotnet CryoFall_Server.dll loadOrNew"
apt-get install screen unzip
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt-get update; \
  sudo apt-get install -y apt-transport-https && \
  sudo apt-get update && \
  sudo apt-get install -y dotnet-runtime-5.0
cd /home
wget https://atomictorch.com/Files/CryoFall_Server_v1.31.8.1.zip
unzip CryoFall_Server_v1.31.8.1.zip
cd /home/CryoFall_Server_v1.31.8.1/Binaries/Server
screen -dmS $screen_cryofall
screen -x -S $screen_cryofall -p 0 -X stuff "$cmd"
screen -x -S $screen_cryofall -p 0 -X stuff $'\n'
screen -x -S $screen_cryofall -p 0 -X stuff $'exit'
screen -r -s $screen_cryofall